### ISSUE TITLE
Screenshots/examples/demo ?

### ISSUE THREAD

**Issue by ataraskov** [nemirlev/zenmoney-dashboard#1]
Hello, would be nice if you can show few screenshots for this project. Thank you in advance.

**Comment by nemirlev** [comment]
Hello.

Sory for long answer. It is very difficult to take a screenshot in Grafana, since personal data is everywhere, and if you close them then it will lose its meaning, since it will not be clear what is reflected.

**Comment by ataraskov** [comment]
I see, your point makes sense.
