### ISSUE TITLE
WSL2 based docker: no matching manifest for linux/amd64 in the manifest list entries.

### ISSUE THREAD

**Issue by rusnino** [nemirlev/zenmoney-dashboard#2]
Привет Лев,
Не совсем разбираюсь какие есть варианты для меня, но судя по всему контейнер собран для платформ linux/arm64/v8.
Запустить хотел в WSL2, с установленным в Windows 11 Docker Desktop (в режиме Linux Containers).
Докер ожидает контейнер для платформы linux/amd64
 
```
latest: Pulling from nemirlev/zenexport
docker: no matching manifest for linux/amd64 in the manifest list entries.
See 'docker run --help'.
```

**Comment by nemirlev** [comment]
Привет. 

Ты можешь самостоятельно собрать image под нужную платформу, используется - https://github.com/nemirlev/zenexport.  Там должно быть достаточно сделать build и задать имя для image, его меняешь в docker-compose, в этом репозитории. 

Если будут сложности, напиши мне здесь, я соберу.

**Comment by rusnino** [comment]
Да сделали, но ты можешь и в свой докер хаб под разные платформы сбилдить, для большей универсальности.

Фидбек: три контейнера были запущены в 18:41, однако импорт у zenexport начался только в 19:11, до этого было непонятно что происходит.
Фидбек2: у меня несколько валют, Рубли\Тенге\Доллары, кажется дашборда не умеет различать их, рисует многомиллионные ежемесячные доходы и расходы в рублях.. (до появления тенге - всё выглядело вроде как правильно)

**Comment by nemirlev** [comment]
Да, в планах сделать под разные платформы. В марте добавлю

1. А сколько примерно транзакций? Вообще статусы есть на каждом этапе, после первого запуска контейнера происходит сразу запуск импорта, потом раз в пол часа. 
2. У меня две валюты, которые использую, но конвертация в рубли корректная вроде. Подумаю что можно сделать. Проблема во всех чартах, или только в определенных?

**Comment by rusnino** [comment]
Привет,
1. а где посмотреть сколько транзакций и какие ты имел ввиду? у меня там данные активно вносятся с 2021 года. К слову сейчас после рестарта хоста, снова запустил Docker Desktop и запустил заново весь проект - быстро всё поднялось

2. Проблема кажется во всех чартах, потому что многие категории заафекчены. Напиши как в личке связаться, пришлю скриншот. Можешь сам в телегу написать на одноименный никнейм.

**Comment by nemirlev** [comment]
Связались в личке, тикет закрыл. Комментарии в проработку взял.
