### ISSUE TITLE
Не могу подключить Промсвязьбанк

### ISSUE THREAD

**Issue by Aleksandr-ShAM** [nemirlev/zenmoney-dashboard#3]
Зарегался в дзенмани, пытаюсь подключить банк, ввожу данные аккаунта, с банка приходит пуш сообщение, вставляется в поле, подтверждаю, выдаёт ошибку:
Не удалось подключить Промсвязьбанк
Версия 116
Можно это как-то победить?

**Comment by nemirlev** [comment]
У меня этот же банк. Все корректно. 

Зайдите в подключение, там есть кнопка "отправить лог разработчикам", они смогут оперативно помочь разобраться. Так же есть чат в ТГ, с разработчиками - https://t.me/zenmoneychat

**Comment by Aleksandr-ShAM** [comment]
Связывался через онлайн чат, отправлял лог, не раз и не вчера, уже с месяц пытаюсь победить это приложение. Пуш сообщения приходят, но дзен мани на них вообще не реагирует, приложение не в режиме сна/гибернации и прочей пепелации, все разрешения выданы и актуальны, есть другое приложение, оно нормально подхватывает все пуши, при том, что намного примитивнее чем дзен-мани.
В дзен-мани не могу добавить банк, думаю хрен с ним, добавлю ручками счёт, а там карта и хотя бы пуш сообщения будут считываться, тоже хрен, просто ноль реакции

**Comment by nemirlev** [comment]
@Aleksandr-ShAM напишите мне в телеграмм - nemirlev
